package com.lgorev.ksuonlineeducation.infrostructure.wowza.models

data class LiveStreamX(
    val aspect_ratio_height: Int?,
    val aspect_ratio_width: Int?,
    val billing_mode: String?,
    val broadcast_location: String?,
    val closed_caption_type: String?,
    val connection_code: String?,
    val connection_code_expires_at: String?,
    val created_at: String?,
    val delivery_method: String?,
    val delivery_protocols: List<String>?,
    val encoder: String?,
    val hosted_page: Boolean?,
    val hosted_page_sharing_icons: Boolean?,
    val hosted_page_title: String?,
    val hosted_page_url: String?,
    val id: String?,
    val low_latency: Boolean?,
    val name: String?,
    val player_countdown: Boolean?,
    val player_embed_code: String?,
    val player_hls_playback_url: String?,
    val player_id: String?,
    val player_responsive: Boolean?,
    val player_type: String?,
    val recording: Boolean?,
    val source_connection_information: SourceConnectionInformation?,
    val stream_targets: List<StreamTarget>?,
    val target_delivery_protocol: String?,
    val transcoder_type: String?,
    val updated_at: String?,
    val use_stream_source: Boolean?
)