package com.lgorev.ksuonlineeducation.repository.trainingdirection

import org.springframework.data.repository.CrudRepository

interface SubjectForEntranceRepository : CrudRepository<SubjectsForEntranceEntity, SubjectsForEntranceId>